### ISSUE TITLE
How do I execute this :$ mkdir build $ cd build $ cmake -DCMAKE_INSTALL_PREFIX=/usr .. $ make $ make package $ make repackage $ sudo dpkg -i ifm3d-pcl-viewer_0.1.0_amd64.deb ................ I cannot execute make command. Please suggest

### ISSUE THREAD

**Issue by sab3rclaw** [lovepark/ifm3d-pcl-viewer#3]

**Comment by tpanzarella** [comment]
I am not entirely sure about what you are asking. Could you post a more specific question in the body of the issue? It sounds like you are having an issue building the software. Maybe you can paste in the terminal output you are seeing so that we can try to help?

Also, there are binaries available for `ifm3d-pcl-viewer`. The instructions shown [here](https://github.com/ifm/ifm3d#installing-the-software) should be able to get you going. HTH.

**Comment by sab3rclaw** [comment]
saberclaw@saberclaw-Aurora-R4:~/ifm3d-pcl-viewer/build$ make repackage
Scanning dependencies of target repackage
Processing input file: /home/saberclaw/ifm3d-pcl-viewer/build/*.deb
Working directory is: /tmp/ifm3d-pcl-viewer-deb-LUXjn8
Extracting /home/saberclaw/ifm3d-pcl-viewer/build/*.deb to /tmp/ifm3d-pcl-viewer-deb-LUXjn8
dpkg-deb: error: failed to read archive '/home/saberclaw/ifm3d-pcl-viewer/build/*.deb': No such file or directory
Traceback (most recent call last):
  File "./ifm3d-pcl-viewer-dpkg-deps.py", line 218, in <module>
    sys.exit(main())
  File "./ifm3d-pcl-viewer-dpkg-deps.py", line 210, in main
    retval = dpkg.run()
  File "./ifm3d-pcl-viewer-dpkg-deps.py", line 63, in run
    retval = self.extract_deb()
  File "./ifm3d-pcl-viewer-dpkg-deps.py", line 194, in extract_deb
    self.deb_file_tmp_])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['dpkg-deb', '-x', '/home/saberclaw/ifm3d-pcl-viewer/build/*.deb', '/tmp/ifm3d-pcl-viewer-deb-LUXjn8']' returned non-zero exit status 2
CMakeFiles/repackage.dir/build.make:57: recipe for target 'CMakeFiles/repackage' failed
make[3]: *** [CMakeFiles/repackage] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/repackage.dir/all' failed
make[2]: *** [CMakeFiles/repackage.dir/all] Error 2
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/repackage.dir/rule' failed
make[1]: *** [CMakeFiles/repackage.dir/rule] Error 2
Makefile:186: recipe for target 'repackage' failed

What should I do

**Comment by tpanzarella** [comment]
The `make repackage` step, repackages an already built debian file with the proper control information expressing its dependencies. In your case, it looks like the debian file was never built. It is referencing `.deb`. Have you built the code successfully and built the debian successfully? These are required prerequisites to running `make repackage`.

**Comment by theseankelly** [comment]
Closing old issue -- if help is still required please reactivate and include the requested information.
